#!/usr/bin/env python3
import RPi.GPIO as GPIO

ALIVE_PIN = 5


"""
Once started PIN10 becomes HIGH,
so RPI state can be check by robot controller.
"""
GPIO.setmode(GPIO.BCM)
GPIO.setup(ALIVE_PIN, GPIO.OUT)
GPIO.output(ALIVE_PIN, GPIO.HIGH)

