openapi: 3.0.1
info:
  title: Auth API
  description: Auth API
  version: 1.0.0
servers:
- url: http://127.0.0.1
paths:
  /v1/users:
    get:
      summary: Get users
      operationId: auth.api.get_users
      responses:
        200:
          $ref: '#/components/responses/UserList'
    post:
      summary: Create user
      operationId: auth.api.create_user
      requestBody:
        $ref: '#/components/requestBodies/CreateUser'
      responses:
        200:
          $ref: '#/components/responses/Default'
  /v1/login:
    post:
      summary: Login user
      operationId: auth.api.login
      requestBody:
        $ref: '#/components/requestBodies/Login'
      responses:
        200:
          $ref: '#/components/responses/Login'
        400:
          $ref: '#/components/responses/400BadRequest'
        401:
          $ref: '#/components/responses/401Unauthorized'
        default:
          $ref: '#/components/responses/500InternalError'
  /v1/check:
    post:
      summary: Check token
      operationId: auth.api.check
      requestBody:
        $ref: '#/components/requestBodies/CheckToken'
      responses:
        200:
          $ref: '#/components/responses/Token'
        401:
          $ref: '#/components/responses/401Unauthorized'
  /v1/logout:
    delete:
      summary: Logout current logged in user session
      operationId: auth.api.logout
      responses:
        200:
          $ref: '#/components/responses/Default'
        401:
          $ref: '#/components/responses/401Unauthorized'
        default:
          $ref: '#/components/responses/500InternalError'

components:
  requestBodies:
    Login:
      description: Login request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginRequestContent'
    CreateUser:
      description: Create user request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateUserContent'
    CheckToken:
      description: Check token request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CheckTokenResponseContent'
  responses:
    Default:
      description: Generic
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DefaultResponseContent'
    401Unauthorized:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DefaultResponseContent'
    400BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DefaultResponseContent'
    500InternalError:
      description: Unexpected error
    Login:
      description: Login successful
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginResponseContent'
    Logout:
      description: Logout successful
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DefaultResponseContent'
    Login:
      description: Login successful
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginResponseContent'
    UserList:
      description: User list
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserListResponseContent'
    Token:
      description: Token valid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CheckTokenResponseContent'
  schemas:
    DefaultResponseContent:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
    LoginRequestContent:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    LoginResponseContent:
      type: object
      properties:
        token:
          type: string
        admin:
          type: boolean
    UserListResponseContent:
      type: object
      properties:
        users:
          type: array
          items:
            type: object
            properties:
              username:
                type: string
              admin:
                type: boolean
    CreateUserContent:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        admin:
          type: boolean
    CheckTokenResponseContent:
      type: object
      properties:
        token:
          type: object
